Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,6 +53,7 @@ jobs:
                 root: /tmp
                 paths:
                   - manifest.yml
+                  - /duild/
     test:
         executor: ci-executor
         steps:
@@ -83,12 +84,6 @@ jobs:
                   cp -r /tmp/build/ .
                   cp /tmp/manifest.yml .
                   cf push --no-start fheo-dark -f manifest.yml -n dark
-                  # Verify new version is working on dark URL.
-                  HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://fheo-dark.app.cloud.gov/`
-                  if [ "$HTTPCODE" -ne 200 ];then
-                    echo "dark route note available, failing deploy"
-                    exit 1
-                  fi
                   # Pass CircleCI variables to Cloud Foundry (optional)
                   # cf set-env <app-name-dark> circle_build_num ${CIRCLE_BUILD_NUM}
                   # cf set-env <app-name-dark> circle_commit ${CIRCLE_SHA1}
@@ -97,6 +92,12 @@ jobs:
                   # cf set-env <app-name-dark> circle_repo ${CIRCLE_PROJECT_REPONAME}
                   # Start the application
                   cf start fheo-dark
+                   # Verify new version is working on dark URL.
+                  HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://fheo-dark.app.cloud.gov/`
+                  if [ "$HTTPCODE" -ne 200 ];then
+                    echo "dark route note available, failing deploy"
+                    exit 1
+                  fi
                   # Ensure dark route is exclusive to dark app
                   cf unmap-route fheo app.cloud.gov -n dark || echo "Dark Route Already exclusive"
     live-deploy:
